#!/usr/bin/env python3
"""Generates lookup tables, 3D object data and the font for the demo.

Outputs (included by src/main.asm):
  src/gen_tables.inc   sine / perspective / mask / dither / light tables
  src/gen_objects.inc  vertices, edges, faces (+normals) of each object
  src/gen_font.inc     8x8 font for ASCII 0x20..0x5F
"""
import glob
import itertools
import math
import os
import sys

ZOFF = 160          # must match ZOFF in main.asm
RADIUS = 54         # circumradius of every object (keeps projection inside 128x128)
NORMAL_SCALE = 64

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src')
MODELS = os.path.join(HERE, '..', 'models')

sys.path.insert(0, HERE)
import obj2inc  # noqa: E402


def db_lines(values, per_line=16, prefix='    db '):
    out = []
    for i in range(0, len(values), per_line):
        out.append(prefix + ','.join(str(v) for v in values[i:i + per_line]))
    return '\n'.join(out)


# ---------------------------------------------------------------- tables

def gen_tables():
    lines = ['; generated by tools/gen_tables.py - do not edit', '']

    # quarter squares for signed multiply: a*b = sq(a+b) - sq(a-b), sq(n) = n*n/4
    # sum table   : index a+b+256      (0..510)
    # diff table  : index (a-b) as 9-bit two's complement
    def sq(n):
        return (n * n) // 4
    sqs = [sq(i - 256) for i in range(512)]
    sqd = [sq(i if i < 256 else i - 512) for i in range(512)]
    lines += ['; quarter square tables (each 512 bytes, low bytes then high bytes)',
              'sqs_lo:', db_lines([v & 0xFF for v in sqs]),
              'sqs_hi:', db_lines([v >> 8 for v in sqs]),
              'sqd_lo:', db_lines([v & 0xFF for v in sqd]),
              'sqd_hi:', db_lines([v >> 8 for v in sqd]), '']

    sin = [round(127 * math.sin(2 * math.pi * i / 256)) for i in range(256)]
    lines += ['; sin(i*2pi/256)*127, signed. cos(a) = sin(a+64)', 'sin_table:',
              db_lines(sin), '']

    recip = []
    for z in range(256):
        recip.append(127 if z == 0 else min(127, round(64 * ZOFF / z)))
    lines += ['; perspective factor: 64*%d/z  (screen = v*f/64)' % ZOFF, 'recip_table:',
              db_lines(recip), '']

    # masks: one 32-byte block (aligned to 32 in main.asm)
    lmask = [0xFF >> i for i in range(8)]
    rmask = [(0xFF << (7 - i)) & 0xFF for i in range(8)]
    bitmask = [0x80 >> i for i in range(8)]
    lines += ['; left span mask, right span mask, single pixel mask (8 each)', 'mask_table:',
              db_lines(lmask + rmask + bitmask + [0] * 8), '']

    # ordered dither (4x4 Bayer): 17 levels x 4 rows
    bayer = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]
    dither = []
    for level in range(17):
        for row in range(4):
            b = 0
            for x in range(8):
                if bayer[row][x & 3] < level:
                    b |= 0x80 >> x
            dither.append(b)
    lines += ['; 4x4 Bayer dither patterns, 17 levels x 4 rows', 'dither_table:',
              db_lines(dither), '']

    # light: S = dot(lobj, normal) in [-6096, 6096]; index = (S+6144)>>8
    levels = []
    for idx in range(48):
        s = idx * 256 + 128 - 6144
        i = max(-1.0, min(1.0, s / 6096.0))
        lv = round(1 + 15 * (i + 0.6) / 1.6)
        lv = max(1, min(16, lv))
        levels.append(lv * 4)
    lines += ['; light intensity index -> dither level*4', 'level_table:',
              db_lines(levels), '']
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------- objects

def vsub(a, b):
    return [a[i] - b[i] for i in range(3)]


def cross(a, b):
    return [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]]


def dot(a, b):
    return sum(a[i] * b[i] for i in range(3))


def norm(a):
    n = math.sqrt(dot(a, a))
    return [c / n for c in a]


def hull_faces(pts):
    """Faces of a convex polyhedron: list of vertex index lists, ordered so that
    (v1-v0)x(v2-v0) points INTO the object (-> on screen visible faces have a
    negative 2D cross product, see face_visible in main.asm)."""
    n = len(pts)
    faces = []
    seen = set()
    eps = 1e-6
    for i, j, k in itertools.combinations(range(n), 3):
        nrm = cross(vsub(pts[j], pts[i]), vsub(pts[k], pts[i]))
        if dot(nrm, nrm) < eps:
            continue
        nrm = norm(nrm)
        d = dot(nrm, pts[i])
        side = [dot(nrm, p) - d for p in pts]
        if all(s <= eps for s in side):
            pass
        elif all(s >= -eps for s in side):
            nrm = [-c for c in nrm]
            d = -d
        else:
            continue
        on = tuple(sorted(m for m in range(n) if abs(dot(nrm, pts[m]) - d) < 1e-4))
        if on in seen:
            continue
        seen.add(on)
        # order around centroid
        c = [sum(pts[m][a] for m in on) / len(on) for a in range(3)]
        u = norm(vsub(pts[on[0]], c))
        w = cross(nrm, u)
        ordered = sorted(on, key=lambda m: math.atan2(dot(vsub(pts[m], c), w),
                                                       dot(vsub(pts[m], c), u)))
        # want cross(v1-v0, v2-v0) . outward_normal < 0
        cr = cross(vsub(pts[ordered[1]], pts[ordered[0]]), vsub(pts[ordered[2]], pts[ordered[0]]))
        if dot(cr, nrm) > 0:
            ordered.reverse()
        faces.append((ordered, nrm))
    return faces


def make_object(name, label, pts_f):
    """Convex polyhedron from a point cloud."""
    r = max(math.sqrt(dot(p, p)) for p in pts_f)
    pts = [[c * RADIUS / r for c in p] for p in pts_f]
    faces = [(f, [int(round(c * NORMAL_SCALE)) for c in n]) for f, n in hull_faces(pts)]
    ipts = [[int(round(c)) for c in p] for p in pts]
    edges = set()
    for f, _ in faces:
        for a, b in zip(f, f[1:] + f[:1]):
            edges.add((min(a, b), max(a, b)))
    return emit_object(name, label, ipts, sorted(edges), faces)


def emit_object(name, label, ipts, edges, faces):
    """faces: list of (vertex indices, integer normal x NORMAL_SCALE)"""
    assert len(ipts) <= 128 and len(edges) <= 255 and len(faces) <= 255
    out = []
    out.append('%s:' % label)
    out.append('    dw %s_name' % label)
    out.append('    db %d' % len(ipts))
    out.append('    dw %s_vtx' % label)
    out.append('    db %d' % len(edges))
    out.append('    dw %s_edge' % label)
    out.append('    db %d' % len(faces))
    out.append('    dw %s_face' % label)
    out.append('%s_vtx:   ; x,y,z' % label)
    for p in ipts:
        out.append('    db %d,%d,%d' % tuple(p))
    out.append('%s_edge:  ; vertex index pairs' % label)
    out.append(db_lines(['%d,%d' % e for e in edges], per_line=8))
    out.append('%s_face:  ; n, indices..., normal x,y,z (x%d)' % (label, NORMAL_SCALE))
    for f, nv in faces:
        out.append('    db %d, %s, %d,%d,%d' % (len(f), ','.join(str(v) for v in f), *nv))
    out.append('%s_name:' % label)
    out.append('    db "%-12s",0' % name)
    out.append('')
    print("  %-13s %3d vertices %3d edges %3d faces" % (name, len(ipts), len(edges), len(faces)))
    return '\n'.join(out)


def gen_objects():
    phi = (1 + math.sqrt(5)) / 2
    cube = [[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)]
    octa = [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]]
    ico = []
    for a in (-1, 1):
        for b in (-phi, phi):
            ico += [[0, a, b], [a, b, 0], [b, 0, a]]
    dode = [[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)]
    for a in (-1, 1):
        for b in (-1 / phi, 1 / phi):
            dode += [[0, a * phi, b], [b, 0, a * phi], [a * phi, b, 0]]
    # pyramid with square base (slightly lifted so it's centred)
    pyr = [[-1, -0.6, -1], [1, -0.6, -1], [1, -0.6, 1], [-1, -0.6, 1], [0, 1.1, 0]]

    objs = [
        ('CUBE', 'obj_cube', cube),
        ('PYRAMID', 'obj_pyramid', pyr),
        ('OCTAHEDRON', 'obj_octa', octa),
        ('ICOSAHEDRON', 'obj_icosa', ico),
        ('DODECAHEDRON', 'obj_dodeca', dode),
    ]
    bodies = [make_object(name, label, pts) for name, label, pts in objs]
    labels = [label for _, label, _ in objs]

    # user models: models/*.obj (see tools/obj2inc.py)
    for path in sorted(glob.glob(os.path.join(MODELS, '*.obj'))):
        label = obj2inc.label_from_path(path)
        if label in labels:
            raise SystemExit("error: duplicate model label %s" % label)
        try:
            v, e, f, st = obj2inc.convert(path)
        except obj2inc.ModelError as ex:
            raise SystemExit("error: %s" % ex)
        if st['dropped'] or st['split']:
            print("  (%s: %d degenerate faces dropped, %d concave faces split)" %
                  (os.path.basename(path), st['dropped'], st['split']))
        bodies.append(emit_object(obj2inc.name_from_path(path), label, v, e, f))
        labels.append(label)
    if len(labels) > 255:
        raise SystemExit("error: too many objects")

    parts = ['; generated by tools/gen_tables.py - do not edit', '',
             'NUM_OBJECTS equ %d' % len(labels), '', 'object_table:']
    for label in labels:
        parts.append('    dw %s' % label)
    parts.append('')
    parts += bodies
    return '\n'.join(parts) + '\n'


# ---------------------------------------------------------------- font

FONT = {
    ' ': ['     '] * 7,
    '!': ['  #  ', '  #  ', '  #  ', '  #  ', '  #  ', '     ', '  #  '],
    '(': ['   # ', '  #  ', ' #   ', ' #   ', ' #   ', '  #  ', '   # '],
    ')': [' #   ', '  #  ', '   # ', '   # ', '   # ', '  #  ', ' #   '],
    '+': ['     ', '  #  ', '  #  ', '#####', '  #  ', '  #  ', '     '],
    ',': ['     ', '     ', '     ', '     ', '  ## ', '   # ', '  #  '],
    '-': ['     ', '     ', '     ', '#####', '     ', '     ', '     '],
    '.': ['     ', '     ', '     ', '     ', '     ', ' ##  ', ' ##  '],
    '/': ['    #', '   # ', '   # ', '  #  ', ' #   ', ' #   ', '#    '],
    ':': ['     ', ' ##  ', ' ##  ', '     ', ' ##  ', ' ##  ', '     '],
    '0': [' ### ', '#   #', '#  ##', '# # #', '##  #', '#   #', ' ### '],
    '1': ['  #  ', ' ##  ', '  #  ', '  #  ', '  #  ', '  #  ', ' ### '],
    '2': [' ### ', '#   #', '    #', '   # ', '  #  ', ' #   ', '#####'],
    '3': ['#####', '   # ', '  #  ', '   # ', '    #', '#   #', ' ### '],
    '4': ['   # ', '  ## ', ' # # ', '#  # ', '#####', '   # ', '   # '],
    '5': ['#####', '#    ', '#### ', '    #', '    #', '#   #', ' ### '],
    '6': ['  ## ', ' #   ', '#    ', '#### ', '#   #', '#   #', ' ### '],
    '7': ['#####', '    #', '   # ', '  #  ', ' #   ', ' #   ', ' #   '],
    '8': [' ### ', '#   #', '#   #', ' ### ', '#   #', '#   #', ' ### '],
    '9': [' ### ', '#   #', '#   #', ' ####', '    #', '   # ', ' ##  '],
    'A': [' ### ', '#   #', '#   #', '#####', '#   #', '#   #', '#   #'],
    'B': ['#### ', '#   #', '#   #', '#### ', '#   #', '#   #', '#### '],
    'C': [' ### ', '#   #', '#    ', '#    ', '#    ', '#   #', ' ### '],
    'D': ['###  ', '#  # ', '#   #', '#   #', '#   #', '#  # ', '###  '],
    'E': ['#####', '#    ', '#    ', '#### ', '#    ', '#    ', '#####'],
    'F': ['#####', '#    ', '#    ', '#### ', '#    ', '#    ', '#    '],
    'G': [' ### ', '#   #', '#    ', '# ###', '#   #', '#   #', ' ####'],
    'H': ['#   #', '#   #', '#   #', '#####', '#   #', '#   #', '#   #'],
    'I': [' ### ', '  #  ', '  #  ', '  #  ', '  #  ', '  #  ', ' ### '],
    'J': ['  ###', '   # ', '   # ', '   # ', '   # ', '#  # ', ' ##  '],
    'K': ['#   #', '#  # ', '# #  ', '##   ', '# #  ', '#  # ', '#   #'],
    'L': ['#    ', '#    ', '#    ', '#    ', '#    ', '#    ', '#####'],
    'M': ['#   #', '## ##', '# # #', '# # #', '#   #', '#   #', '#   #'],
    'N': ['#   #', '#   #', '##  #', '# # #', '#  ##', '#   #', '#   #'],
    'O': [' ### ', '#   #', '#   #', '#   #', '#   #', '#   #', ' ### '],
    'P': ['#### ', '#   #', '#   #', '#### ', '#    ', '#    ', '#    '],
    'Q': [' ### ', '#   #', '#   #', '#   #', '# # #', '#  # ', ' ## #'],
    'R': ['#### ', '#   #', '#   #', '#### ', '# #  ', '#  # ', '#   #'],
    'S': [' ####', '#    ', '#    ', ' ### ', '    #', '    #', '#### '],
    'T': ['#####', '  #  ', '  #  ', '  #  ', '  #  ', '  #  ', '  #  '],
    'U': ['#   #', '#   #', '#   #', '#   #', '#   #', '#   #', ' ### '],
    'V': ['#   #', '#   #', '#   #', '#   #', '#   #', ' # # ', '  #  '],
    'W': ['#   #', '#   #', '#   #', '# # #', '# # #', '# # #', ' # # '],
    'X': ['#   #', '#   #', ' # # ', '  #  ', ' # # ', '#   #', '#   #'],
    'Y': ['#   #', '#   #', ' # # ', '  #  ', '  #  ', '  #  ', '  #  '],
    'Z': ['#####', '    #', '   # ', '  #  ', ' #   ', '#    ', '#####'],
}


def gen_font():
    lines = ['; generated by tools/gen_tables.py - do not edit',
             '; 8x8 font, ASCII 0x20..0x5F (64 chars x 8 bytes)', 'font_data:']
    for code in range(0x20, 0x60):
        g = FONT.get(chr(code), ['     '] * 7)
        rows = []
        for r in g:
            b = 0
            for x, ch in enumerate(r):
                if ch == '#':
                    b |= 0x40 >> x       # 5 pixels at columns 1..5
            rows.append(b)
        rows.append(0)
        lines.append('    db %s   ; %r' % (','.join('0x%02X' % b for b in rows), chr(code)))
    return '\n'.join(lines) + '\n'


def main():
    files = {
        'gen_tables.inc': gen_tables(),
        'gen_objects.inc': gen_objects(),
        'gen_font.inc': gen_font(),
    }
    for name, text in files.items():
        path = os.path.join(SRC, name)
        with open(path, 'w') as f:
            f.write(text)
        print("wrote", os.path.relpath(path))


if __name__ == '__main__':
    main()
